export const VAN_MIEU_BOUNDS = {
  center: [21.02875, 105.8360],
  defaultZoom: 17,
  minZoom: 16,
  maxZoom: 19,
  // Bounding box restricting map panning to Van Mieu and its immediate surrounding
  maxBounds: [
    [21.0230, 105.8300], // Southwest
    [21.0340, 105.8420], // Northeast
  ],
}

export const MAP_LOCATIONS = [
  {
    id: 'location-van-mieu-gate',
    order: 1,
    name: 'Cổng Văn Miếu',
    tagline: 'Lối vào chính quần thể',
    lat: 21.02758,
    lng: 105.83551,
    image: '/images/heritage/van-mieu-gate.webp',
    description: 'Lối vào đầu tiên mở ra trục kiến trúc và không gian đạo học của quần thể.',
    detailPath: '/Explore/Cong-Van-Mieu',
    distanceEst: '10 m',
  },
  {
    id: 'location-dai-trung-gate',
    order: 2,
    name: 'Cổng Đại Trung',
    tagline: 'Cổng lớp thứ hai',
    lat: 21.02817,
    lng: 105.83574,
    image: '/images/heritage/dai-trung-gate.webp',
    description: 'Cánh cổng dẫn vào không gian trung tâm, rèn đức luyện tài.',
    detailPath: '/Explore/Cong-Dai-Trung',
    distanceEst: '46 m',
  },
  {
    id: 'interpret',
    order: 3,
    name: 'Khuê Văn Các',
    tagline: 'Biểu tượng văn chương',
    lat: 21.02868,
    lng: 105.83592,
    image: '/images/heritage/khue-van-cac.webp',
    description: 'Biểu tượng của văn chương, trí tuệ và Thủ đô Hà Nội ngàn năm văn hiến.',
    detailPath: '/Explore/Khue-Van-Cac',
    distanceEst: '32 m',
  },
  {
    id: 'location-dai-thanh-gate',
    order: 4,
    name: 'Cổng Đại Thành',
    tagline: 'Lối vào khu điện thờ',
    lat: 21.02908,
    lng: 105.83608,
    image: '/images/heritage/dai-thanh-gate.webp',
    description: 'Cánh cổng đánh dấu lối vào khu điện thờ trang nghiêm và sân Đại Bái.',
    detailPath: '/Explore/Cong-Dai-Thanh',
    distanceEst: '95 m',
  },
  {
    id: 'location-dien-dai-thanh',
    order: 5,
    name: 'Điện Đại Thành',
    tagline: 'Trung tâm thờ tự',
    lat: 21.02935,
    lng: 105.83619,
    image: '/images/heritage/dien-dai-thanh.webp',
    description: 'Không gian thờ Khổng Tử và các bậc hiền triết Nho học trong cấu trúc sơn son.',
    detailPath: '/Explore/Dien-Dai-Thanh',
    distanceEst: '120 m',
  },
  {
    id: 'location-thai-hoc-gate',
    order: 6,
    name: 'Cổng Thái Học',
    tagline: 'Chuyển tiếp Quốc Tử Giám',
    lat: 21.02951,
    lng: 105.83626,
    image: '/images/heritage/thai-hoc-gate.webp',
    description: 'Lối chuyển tiếp vào khu vực tưởng niệm truyền thống giáo dục Quốc học.',
    detailPath: '/Explore/Cong-Thai-Hoc',
    distanceEst: '185 m',
  },
  {
    id: 'location-thai-hoc-house',
    order: 7,
    name: 'Nhà Thái Học',
    tagline: 'Truyền thống giáo dục',
    lat: 21.02998,
    lng: 105.83643,
    image: '/images/heritage/thai-hoc-building.webp',
    description: 'Công trình tôn vinh Quốc Tử Giám và những người thầy tiêu biểu của dân tộc.',
    detailPath: '/Explore/Nha-Thai-Hoc',
    distanceEst: '210 m',
  },
  {
    id: 'location-bell-drum-tower',
    order: 8,
    name: 'Lầu Chuông – Lầu Trống',
    tagline: 'Cặp công trình cân xứng',
    lat: 21.02996,
    lng: 105.83631,
    image: '/images/heritage/bell-drum-tower.webp',
    description: 'Cặp công trình đăng đối hai bên sân Thái Học tạo nhịp nghi lễ trang nghiêm.',
    detailPath: '/Explore/Lau-Chuong-Lau-Trong',
    distanceEst: '235 m',
  },
  {
    id: 'location-octagonal-house',
    order: 9,
    name: 'Nhà Bát Giác',
    tagline: 'Kiến trúc tám cạnh',
    lat: 21.02891,
    lng: 105.83533,
    image: '/images/heritage/octagonal-house.webp',
    description: 'Không gian kiến trúc tám cạnh giàu biểu tượng giữa cảnh quan cây xanh.',
    detailPath: '/Explore/Nha-Bat-Giac',
    distanceEst: '260 m',
  },
  {
    id: 'location-phuong-dinh',
    order: 10,
    name: 'Phương Đình (Hồ Văn)',
    tagline: 'Bên bờ Hồ Văn',
    lat: 21.02672,
    lng: 105.83630,
    image: '/images/heritage/phuong-dinh.webp',
    description: 'Điểm dừng chân kết nối cảnh quan mặt nước Hồ Văn và trục chính di tích.',
    detailPath: '/Explore/Phuong-Dinh',
    distanceEst: '175 m',
  },
]
