export const VAN_MIEU_BOUNDS = { // Xuất ra ngoài để không ấy lại Data
  center: [21.02875, 105.8360], // Kinh độ , Vĩ độ 
  defaultZoom: 17,
  minZoom: 16,
  maxZoom: 19,
  // Bounding box restricting map panning to Van Mieu and its immediate surrounding
  maxBounds: [
    [21.0230, 105.8300], // Southwest
    [21.0340, 105.8420], // Northeast
  ],
}

export const MAP_LOCATIONS = [
  {
    id: 'location-van-mieu-gate',
    order: 1,
    name: 'Temple of Literature Gate',
    tagline: 'Main entrance to the complex',
    lat: 21.02758,
    lng: 105.83551,
    image: '/images/heritage/van-mieu-gate.webp',
    description: 'The main entrance opens onto the architectural axis and scholarly grounds of the complex.',
    detailPath: '/Explore/Cong-Van-Mieu',
    distanceEst: '10 m',
  },
  {
    id: 'location-dai-trung-gate',
    order: 2,
    name: 'Dai Trung Gate',
    tagline: 'Second courtyard gate',
    lat: 21.02817,
    lng: 105.83574,
    image: '/images/heritage/dai-trung-gate.webp',
    description: 'The gate leads to the central grounds dedicated to virtue and learning.',
    detailPath: '/Explore/Cong-Dai-Trung',
    distanceEst: '46 m',
  },
  {
    id: 'interpret',
    order: 3,
    name: 'Khue Van Pavilion',
    tagline: 'Symbol of literature',
    lat: 21.02868,
    lng: 105.83592,
    image: '/images/heritage/khue-van-cac.webp',
    description: 'A symbol of literature, knowledge, and the scholarly heritage of Hanoi.',
    detailPath: '/Explore/Khue-Van-Cac',
    distanceEst: '32 m',
  },
  {
    id: 'location-dai-thanh-gate',
    order: 4,
    name: 'Dai Thanh Gate',
    tagline: 'Entrance to the sanctuary',
    lat: 21.02908,
    lng: 105.83608,
    image: '/images/heritage/dai-thanh-gate.webp',
    description: 'The gate leads to the solemn sanctuary and ceremonial courtyard.',
    detailPath: '/Explore/Cong-Dai-Thanh',
    distanceEst: '95 m',
  },
  {
    id: 'location-dien-dai-thanh',
    order: 5,
    name: 'Dai Thanh Hall',
    tagline: 'Central sanctuary',
    lat: 21.02935,
    lng: 105.83619,
    image: '/images/heritage/dien-dai-thanh.webp',
    description: 'The sanctuary honors Confucius and the great Confucian scholars.',
    detailPath: '/Explore/Dien-Dai-Thanh',
    distanceEst: '120 m',
  },
  {
    id: 'location-thai-hoc-gate',
    order: 6,
    name: 'Thai Hoc Gate',
    tagline: 'Passage to the Imperial Academy',
    lat: 21.02951,
    lng: 105.83626,
    image: '/images/heritage/thai-hoc-gate.webp',
    description: 'The passage leads to the grounds commemorating national education.',
    detailPath: '/Explore/Cong-Thai-Hoc',
    distanceEst: '185 m',
  },
  {
    id: 'location-thai-hoc-house',
    order: 7,
    name: 'Thai Hoc Hall',
    tagline: 'Educational heritage',
    lat: 21.02998,
    lng: 105.83643,
    image: '/images/heritage/thai-hoc-building.webp',
    description: 'The building honors the Imperial Academy and distinguished Vietnamese teachers.',
    detailPath: '/Explore/Nha-Thai-Hoc',
    distanceEst: '210 m',
  },
  {
    id: 'location-bell-drum-tower',
    order: 8,
    name: 'Bell and Drum Towers',
    tagline: 'Symmetrical towers',
    lat: 21.02996,
    lng: 105.83631,
    image: '/images/heritage/bell-drum-tower.webp',
    description: 'The symmetrical towers frame the Thai Hoc courtyard and its ceremonial space.',
    detailPath: '/Explore/Lau-Chuong-Lau-Trong',
    distanceEst: '235 m',
  },
  {
    id: 'location-octagonal-house',
    order: 9,
    name: 'Octagonal Pavilion',
    tagline: 'Octagonal architecture',
    lat: 21.02891,
    lng: 105.83533,
    image: '/images/heritage/octagonal-house.webp',
    description: 'An octagonal building set among gardens and visitor paths.',
    detailPath: '/Explore/Nha-Bat-Giac',
    distanceEst: '260 m',
  },
  {
    id: 'location-phuong-dinh',
    order: 10,
    name: 'Phuong Dinh Pavilion (Literature Lake)',
    tagline: 'By Literature Lake',
    lat: 21.02672,
    lng: 105.83630,
    image: '/images/heritage/phuong-dinh.webp',
    description: 'A pavilion connecting Literature Lake with the main heritage complex.',
    detailPath: '/Explore/Phuong-Dinh',
    distanceEst: '175 m',
  },
]
